# syntax=docker/dockerfile:1
# Static SPA only (Authentik + API calls are browser/edge; no Node in the image).

FROM oven/bun:1-alpine AS build
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile
COPY . .
# Baked at build; pass the Vite vars you need (see .env.example / src/config/appConfig.ts).
ARG VITE_BASE_PATH=/
ARG VITE_TITLE=ZetaRe
ARG VITE_COMPANY_NAME
ARG VITE_SUPPORT_EMAIL
ARG VITE_VERSION
ARG VITE_MANIFEST_DESCRIPTION
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_OIDC_LOGIN_URL
ARG VITE_OIDC_ISSUER
ARG VITE_OIDC_CLIENT_ID
ARG VITE_OIDC_REDIRECT_URI
ARG VITE_OIDC_END_SESSION_URL
ARG VITE_MIXPANEL_TOKEN
ARG VITE_ENVIRONMENT
ARG VITE_DEV_SERVER_PORT
ENV VITE_BASE_PATH=${VITE_BASE_PATH}
ENV VITE_TITLE=${VITE_TITLE}
ENV VITE_COMPANY_NAME=${VITE_COMPANY_NAME}
ENV VITE_SUPPORT_EMAIL=${VITE_SUPPORT_EMAIL}
ENV VITE_VERSION=${VITE_VERSION}
ENV VITE_MANIFEST_DESCRIPTION=${VITE_MANIFEST_DESCRIPTION}
ENV VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
ENV VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
ENV VITE_OIDC_LOGIN_URL=${VITE_OIDC_LOGIN_URL}
ENV VITE_OIDC_ISSUER=${VITE_OIDC_ISSUER}
ENV VITE_OIDC_CLIENT_ID=${VITE_OIDC_CLIENT_ID}
ENV VITE_OIDC_REDIRECT_URI=${VITE_OIDC_REDIRECT_URI}
ENV VITE_OIDC_END_SESSION_URL=${VITE_OIDC_END_SESSION_URL}
ENV VITE_MIXPANEL_TOKEN=${VITE_MIXPANEL_TOKEN}
ENV VITE_ENVIRONMENT=${VITE_ENVIRONMENT}
ENV VITE_DEV_SERVER_PORT=${VITE_DEV_SERVER_PORT}
RUN bun run build

FROM nginx:1-alpine AS production
COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/nginx.default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
STOPSIGNAL SIGQUIT
CMD ["nginx", "-g", "daemon off;"]
